version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  employee-service:
    build: employee-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=employee_db

volumes:
  mongo_data:
